<!-- Wrapper for the radial gradient background -->
  <div id="sidebar">
    <div id="sidebar-wrapper">
      <!-- Sidebar with logo and menu -->
      <h1 id="sidebar-title"><a href="<?php echo $this->_viewer->baseurl;?>">网站信息管理后台</a></h1>
      <!-- Logo (221px wide) -->
      <a href="<?php echo $this->_viewer->baseurl;?>"><img id="logo" src="<?php echo $this->_viewer->imgpath;?>/logo.png" alt="Simpla Admin logo" /></a>
      <!-- Sidebar Profile links -->
      <div id="profile-links"> 欢迎登陆, <a href="<?php echo $this->_viewer->baseurl . 'a=managermodify&id=' . (isset($userInfo['id']) ? $userInfo['id'] : '');?>" title="编辑个人信息"><?php echo isset($userInfo['username']) ? $userInfo['username'] : '';?></a><br />
        <br />
        <a href="/" target="_blank" title="查看站点首页">查看站点首页</a> | <a href="<?php echo $this->_viewer->baseurl . 'a=loginout';?>">退出</a> </div>
      <ul id="main-nav">
        <!-- Accordion Menu -->
        <li> <a href="<?php echo $this->_viewer->baseurl;?>" class="nav-top-item no-submenu <?php echo ($this->_viewer->menuparent == 'index') ? 'current' : '';?>">
          <!-- Add the class "no-submenu" to menu items with no sub menu -->
          	 后台首页</a> </li>
        
         <li> 
         	<a href="#" class="nav-top-item  <?php echo ($this->_viewer->menuparent == 'basic') ? 'current' : '';?>"> 基础配置 </a>
          	<ul>
          		<li><a href="<?php echo $this->_viewer->baseurl . 'a=webconfig';?>" class="<?php echo ($this->_viewer->menuchild == 'webconfig') ? 'current' : '';?>">站点信息</a></li>
          		<li><a href="<?php echo $this->_viewer->baseurl . 'a=dataconfig';?>" class="<?php echo ($this->_viewer->menuchild == 'dataconfig') ? 'current' : '';?>">站点配置</a></li>
          	</ul>
        </li>
        <?php 
        foreach ($this->_viewer->menus as $k=>$name){
        ?>
        	<li> 
	         	<a href="#" class="nav-top-item  <?php echo ($this->_viewer->menuparent == $k) ? 'current' : '';?>"> <?php echo $name;?>管理 </a>
	          	<ul>
	          		<li><a href="<?php echo $this->_viewer->baseurl . 'a='.$k.'category';?>" class="<?php echo ($this->_viewer->menuchild == $k.'category') ? 'current' : '';?>">类别管理</a></li>
	          		<li><a href="<?php echo $this->_viewer->baseurl . 'a='.$k;?>" class="<?php echo ($this->_viewer->menuchild == $k) ? 'current' : '';?>"><?php echo $name;?>管理</a></li>
		            <li><a href="<?php echo $this->_viewer->baseurl . 'a='.$k.'add';?>" class="<?php echo ($this->_viewer->menuchild == $k.'add') ? 'current' : '';?>">添加<?php echo $name;?></a></li>
	          	</ul>
	        </li>
        <?php 
        }
        ?>
        <li> 
         	<a href="#" class="nav-top-item  <?php echo ($this->_viewer->menuparent == 'manager') ? 'current' : '';?>"> 帐号管理 </a>
          	<ul>
          		<li><a href="<?php echo $this->_viewer->baseurl . 'a=manager';?>" class="<?php echo ($this->_viewer->menuchild == 'manager') ? 'current' : '';?>">帐号管理</a></li>
	            <li><a href="<?php echo $this->_viewer->baseurl . 'a=managermodify&id=' . (isset($userInfo['id']) ? $userInfo['id'] : '');?>" class="<?php echo ($this->_viewer->menuchild == 'managermodify') ? 'current' : '';?>">修改帐号</a></li>
	            <li><a href="<?php echo $this->_viewer->baseurl . 'a=manageradd';?>" class="<?php echo ($this->_viewer->menuchild == 'manageradd') ? 'current' : '';?>">添加管理员</a></li>
          	</ul>
        </li>
        
      </ul>
      <!-- End #main-nav -->
    </div>
  </div>
  <!-- End #sidebar -->