<?php
$this->segment ( 'admin.top' );
$this->segment ( 'admin.nav' );
?>
<div id="main-content">
<div class="content-box"><!-- Start Content Box -->
<div class="content-box-header">
<h3><?php echo (isset($this->_viewer->info)) ? "修改" : "添加";?><?php echo $this->_viewer->menuname;?></h3>
	<ul class="content-box-tabs">
        <li><a href="<?php echo $this->_viewer->baseurl . 'a=cases';?>" class="<?php echo ($this->_viewer->currenttab == 'cases') ? "default-tab" : '';?>"><?php echo $this->_viewer->menuname;?>管理</a></li>
        <li><a href="<?php echo $this->_viewer->baseurl . 'a=casesadd';?>" class="<?php echo ($this->_viewer->currenttab == 'casesadd') ? "default-tab" : '';?>">添加<?php echo $this->_viewer->menuname;?></a></li>
        <?php if(isset($this->_viewer->info)){?>
        <li><a href="#" class="<?php echo ($this->_viewer->currenttab == 'casesmodify') ? "default-tab" : '';?>">修改Product</a></li>
   		<?php }?>
   </ul>
<div class="clear"></div>
</div>
<!-- End .content-box-header -->
<div class="content-box-content">
<div class="tab-content default-tab" id="tab1">
<form name="myform" id="myform" action="<?php echo $this->_viewer->formaction;?>" method="post" enctype="multipart/form-data">
<input type="hidden" name="step" value="2">
<input type="hidden" name="id" value="<?php echo isset($this->_viewer->info) ? $this->_viewer->info['id'] : 0;?>">
<fieldset>
<p><label>所属类别</label>
<?php if (!S::isArray($this->_viewer->class)){
	echo "请先添加类别！";
}else{
?>
	<select name="pid" class="small-input">
		<option value="0">一级目录</option>
		<?php if (S::isArray($this->_viewer->class)){?>
		<?php foreach ($this->_viewer->class as $v){?>
			<option value="<?php echo $v['id'];?>" <?php echo (isset($this->_viewer->info) && $this->_viewer->info['category'] == $v['id']) ? 'selected' : '';?>>
			<?php
			for ($d=0; $d < $v['depth']; $d++){
				echo '&nbsp;&nbsp;|--';
			}
			?>
			<?php echo $v['name'];?>
			</option>
		<?php }?>
		<?php }?>
	</select>
<?php }?>
</p>
<p><label>名称</label> <input class="text-input medium-input"
	type="text" id="small-input" name="title" value="<?php echo isset($this->_viewer->info) ? $this->_viewer->info['title'] : "";?>"/> <span
	class="input-notification png_bg"></span>
	<!-- Classes for input-notification: success, error, information, attention -->
</p>

<p><label>展示主图</label>
	<input type="text" id="url" class="text-input small-input" name="thumbpic" value="<?php echo isset($this->_viewer->info['thumbpic']) ? $this->_viewer->info['thumbpic'] : '';?>"> 
	<div id="queue"></div>
	<input id="data_upload" name="video_upload" type="file" multiple="false">
	<span class="input-notification png_bg information">上传图片最佳尺寸：200px*200px</span>
	<span class="input-notification png_bg information">使用网络图片时请在文本框中填写网络图片地址；使用本地上传时文本框中请留空</span>
</p>
<p><img id="imgshow" src="<?php echo isset($this->_viewer->info['thumbpic']) ? $this->_viewer->info['thumbpic'] : $this->_viewer->imgpath . '/nopic.jpg';?>" width="100" border="0" alt="主图"></p>

<p><label>简介描述</label> 
	<textarea class="text-input textarea medium-input" name="summary" rows="5"><?php echo $this->_viewer->info ? $this->_viewer->info['summary'] : "";?></textarea>
</p>
<p><label>详细内容</label> 
	<textarea class="text-input textarea hide" name="content" cols="79" rows="15"><?php echo isset($this->_viewer->info['content']) ? $this->_viewer->info['content'] : '';?></textarea>
</p>
<p><label>是否直接发布</label>
	<input type="radio" name="status" value="1" <?php echo isset($this->_viewer->info) ? ($this->_viewer->info['status'] ? "checked" : "") : "checked";?>/>直接发布  
	<input type="radio" name="status" value="0" <?php echo (isset($this->_viewer->info) && !$this->_viewer->info['status'] ? "checked" : "");?>/> 暂不发布
</p>

<p><input class="button" type="button" value="提交保存" onClick="return pagejs.setform();"/>
<span id="form_result"></span>
</p>
</fieldset>
<div class="clear"></div>
<!-- End .clear -->
</form>
<span id="pics_model" style="display:none;">第{num}张副图:<input type="text" class="text-input small-input" name="pics{num}"/> <input type="file" name="file_pics{num}"></span>
</div>
<!-- End #tab2 --></div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->

<?php
$this->segment ( 'admin.footer' );
?> 
<script src="<?php echo $this->_viewer->jspath;?>/uploadify/jquery.uploadify.min.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->_viewer->jspath;?>/uploadify/uploadify.css">
<script charset="utf-8" src="<?php echo $this->_viewer->editor;?>/kindeditor-min.js"></script>
<script charset="utf-8" src="<?php echo $this->_viewer->editor;?>/lang/zh_CN.js"></script>
<script type="text/javascript">
var editor;
$(function() {
	editor = KindEditor.create('textarea[name="content"]',{
		newlineTag : 'p',
		minHeight  : '300px',
		uploadJson : '<?php echo $this->_viewer->baseurl . 'a=upload&sign=cases';?>'
	});
});
var pagejs = {
	addPicsSpan : function(){
		var model = $("#pics_model").html();
		var num = $("#picsnum").val();
		num = parseInt(num)+1;
		var reg=new RegExp("{num}","g"); //创建正则RegExp对象  
		model=model.replace(reg,num);  
		$("#pics_box").append("<p>" + model + " <button type=\"button\" onClick=\"pagejs.plusPicsSpan(this);\">-</button></p>");
		$("#picsnum").val(num);
	},
	plusPicsSpan : function(btnObj){
		$(btnObj).parent("p").remove();
	},
	plusFirstPicSpan : function(btnObj){
		$(".pics_first").val('');
	},
	setform : function(){
		if(this.formcheck()) {
			var options = {
			    dataType:	'json',
			    beforeSend: function(){
					$("#form_result").html("正在提交表单，请稍候...");
			    },
			    success: function(data) {
				    data = data.data;
			    	var flag = data[0];
			    	var msg = data[1];
			    	$("#form_result").html(msg);
			    	if(flag){
		    		<?php if(isset($this->_viewer->info)){?>
			    		location.reload();
			    	<?php }else{?>
			    		$("#form_result").append("<a href='<?php echo $this->_viewer->baseurl . '&a=cases';?>'>去管理页查看</a>");
			    		$('#myform').resetForm();
			    	<?php }?>
			    	}
			    }
		    };
			$('#myform').ajaxSubmit(options);
			return false;
		}
		return false;
	},
	formcheck : function(){
		editor.sync();
		if(checkspace($("#myform input[name='title']").val())){
			changeInputTips($("#myform input[name='title']"), "+", "error", "请填写名称");
			return false;
		}else{
			changeInputTips($("#myform input[name='title']"), "-", "error", "");
			changeInputTips($("#myform input[name='title']"), "+", "success", "正确");
		}
		return true;
	}
};
$('#data_upload').uploadify({
	'formData'     : {
		'timestamp' : '<?php echo time();?>',
		'token'     : '<?php echo md5('unique_salt' . time());?>'
	},
	'swf'      : '<?php echo $this->_viewer->jspath;?>/uploadify/uploadify.swf',
	'uploader' : '<?php echo $this->_viewer->baseurl . 'a=upload&sign=cases&dir=image&field=Filedata';?>',
	'onUploadSuccess' : function(file, data, response) {
		var jsonDatas = eval("(" + data + ")");
		if(jsonDatas.error == 1){
			alert(jsonDatas.message);
		}else{
			$("#url").val(jsonDatas.url);
			$("#imgshow").attr('src', jsonDatas.url);
		}
	}
});
</script>