<?php
$this->segment ( 'admin.top' );
$this->segment ( 'admin.nav' );
?>
<div id="main-content">
<div class="content-box"><!-- Start Content Box -->
<div class="content-box-header">
<h3>友情链接</h3>
	<ul class="content-box-tabs">
         <li><a href="<?php echo $this->_viewer->baseurl . 'a=company';?>" class="<?php echo ($this->_viewer->menuchild == 'company') ? "default-tab" : '';?>">友情链接</a></li>
        <li><a href="<?php echo $this->_viewer->baseurl . 'a=companyadd';?>" class="<?php echo ($this->_viewer->menuchild == 'companyadd') ? "default-tab" : '';?>">添加友情链接</a></li>
   </ul>
<div class="clear"></div>
</div>
<!-- End .content-box-header -->
<div class="content-box-content">
<div class="tab-content default-tab" id="tab1">
<form name="myform" id="myform" action="<?php echo $this->_viewer->formaction;?>" method="post">
<input type="hidden" name="step" value="2">
<table>
	<thead>
		<tr>
			<th width="400">链接标题</th>
			<th>链接地址</th>
			<th width="100">操作</th>
		</tr>
	</thead>
	<!-- 
	<tfoot>
		<tr>
			<td colspan="4">
			<div class="bulk-actions align-left"><a class="button" href="javascript:;" onClick="pagejs.setform();">保存修改</a>
				<span id="form_result"></span>
			</div>
			<div class="clear"></div>
			</td>
		</tr>
	</tfoot>
	 -->
	<tbody>
	<?php if (!S::isArray($this->_viewer->list)){?>
		<tr>
			<td colspan="11">暂无信息！</td>
		</tr>
	<?php }else{?>
	<?php foreach ($this->_viewer->list as $k=>$v){?>
		<tr>
			<td><?php echo isset($v['title']) ? $v['title'] : '-';?></td>
			<td><?php echo isset($v['link']) ? $v['link'] : '-';?></td>
			<td align="center">
				<a href="<?php echo $this->_viewer->baseurl . 'a=companymodify&id=' . $k;?>" title="Edit"><img src="<?php echo $this->_viewer->imgpath;?>/icons/pencil.png" alt="Edit" /></a>
				&nbsp;&nbsp;
				<a href="javascript:;" title="Delete" onClick="return pagejs.postDelete('<?php echo $this->_viewer->baseurl . 'a=companydelete&step=2&id=' . $k;?>');"><img src="<?php echo $this->_viewer->imgpath; ?>/icons/cross.png" alt="Delete" /></a>
			</td>
		</tr>
	<?php }?>
	<?php }?>
	
	</tbody>
</table>
</form>

</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->

<?php
$this->segment ( 'admin.footer' );
?> 

<script type="text/javascript">
var pagejs = {
	deleteConfirm : function(){
		return confirm("确定删除该项吗？删除后将无法恢复！");
	},
	postDelete : function(url){
		if(this.deleteConfirm()){
			url += '&callback=?';
			$.getJSON(url, function(data){
				var result = data.data;
				if(result[0] == true)
					location.reload();
				else
					alert(result[1]);
			});
		}
		return false;
	},
	setform : function(){
		var options = {
		    dataType:	'jsonp',
		    beforeSend: function(){
				$("#form_result").html("正在提交表单，请稍候...");
		    },
		    success: function(data) {
			    data = data.data;
		    	var flag = data[0];
		    	var msg = data[1];
		    	$("#form_result").html(msg);
		    	if(flag){
		    		location.reload();
		    	}
		    }
	    };
		$('#myform').ajaxSubmit(options);
		return false;
	}
}
</script>