<?php
$this->segment ( 'admin.top' );
$this->segment ( 'admin.nav' );
?>
<div id="main-content">
<div class="content-box"><!-- Start Content Box -->
<div class="content-box-header">
<h3>站点配置</h3>
	<ul class="content-box-tabs">
   </ul>
<div class="clear"></div>
</div>
<!-- End .content-box-header -->
<div class="content-box-content">
<div class="tab-content default-tab" id="tab1">
<form name="myform" id="myform" action="<?php echo $this->_viewer->formaction;?>" method="post">
<input type="hidden" name="step" value="2">
<fieldset>

<p>
	<label>联系我们：公司地址</label>
	<input class="text-input medium-input" type="text" name="data-contact-address" value="<?php echo isset($this->_viewer->configInfo['data-contact-address']) ? $this->_viewer->configInfo['data-contact-address'] : '';?>"/> 
	<span class="input-notification information png_bg">联系我们-公司地址</span>
</p>
<p>
	<label>联系我们：公司地址英文</label>
	<input class="text-input medium-input" type="text" name="data-contact-address-en" value="<?php echo isset($this->_viewer->configInfo['data-contact-address-en']) ? $this->_viewer->configInfo['data-contact-address-en'] : '';?>"/> 
	<span class="input-notification information png_bg">联系我们-公司地址</span>
</p>
<p>
	<label>联系我们：公司电话</label>
	<input class="text-input medium-input" type="text" name="data-contact-tel" value="<?php echo isset($this->_viewer->configInfo['data-contact-tel']) ? $this->_viewer->configInfo['data-contact-tel'] : '';?>"/> 
	<span class="input-notification information png_bg">联系我们-公司电话</span>
</p>
<p>
	<label>联系我们：公司传真</label>
	<input class="text-input medium-input" type="text" name="data-contact-fax" value="<?php echo isset($this->_viewer->configInfo['data-contact-fax']) ? $this->_viewer->configInfo['data-contact-fax'] : '';?>"/> 
	<span class="input-notification information png_bg">联系我们-公司传真</span>
</p>
<p>
	<label>联系我们：公司邮箱</label>
	<input class="text-input medium-input" type="text" name="data-contact-email" value="<?php echo isset($this->_viewer->configInfo['data-contact-email']) ? $this->_viewer->configInfo['data-contact-email'] : '';?>"/> 
	<span class="input-notification information png_bg">联系我们-公司邮箱</span>
</p>

<p>
	<label>品牌案例PDF下载地址</label>
	<input class="text-input medium-input" type="text" name="data-case-pdf-downurl" value="<?php echo isset($this->_viewer->configInfo['data-case-pdf-downurl']) ? $this->_viewer->configInfo['data-case-pdf-downurl'] : '';?>"/> 
	<span class="input-notification information png_bg">品牌案例PDF下载地址</span>
</p>

<p>
	<label>电子商务PDF下载地址</label>
	<input class="text-input medium-input" type="text" name="data-ecmm-pdf-downurl" value="<?php echo isset($this->_viewer->configInfo['data-ecmm-pdf-downurl']) ? $this->_viewer->configInfo['data-ecmm-pdf-downurl'] : '';?>"/> 
	<span class="input-notification information png_bg">电子商务PDF下载地址</span>
</p>


<p><input class="button" type="button" value="保存配置" onClick="return pagejs.setform();"/><span id="form_result"></span></p>
</fieldset>
<div class="clear"></div>
<!-- End .clear -->
</form>
</div>
<!-- End #tab2 --></div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->
<?php
$this->segment ( 'admin.footer' );
?>

<script type="text/javascript">
var pagejs = {
	setform : function(){
		if(this.formcheck()) {
			var options = {
			    dataType:	'jsonp',
			    beforeSend: function(){
					$("#form_result").html("正在提交表单，请稍候...");
			    },
			    success: function(data) {
				    data = data.data;
			    	var flag = data[0];
			    	var msg = data[1];
			    	$("#form_result").html(msg);
			    	if(flag){
			    		location.reload();
			    	}
			    }
		    };
			$('#myform').ajaxSubmit(options);
			return false;
		}
		return false;
	},
	formcheck : function(){
		return true;
	}
}
</script>