<?php
$this->segment ( 'admin.top' );
$this->segment ( 'admin.nav' );
?>
<div id="main-content">
<div class="content-box"><!-- Start Content Box -->
<div class="content-box-header">
<h3>站点配置</h3>
	<ul class="content-box-tabs">
   </ul>
<div class="clear"></div>
</div>
<!-- End .content-box-header -->
<div class="content-box-content">
<div class="tab-content default-tab" id="tab1">
<form name="myform" id="myform" action="<?php echo $this->_viewer->formaction;?>" method="post">
<input type="hidden" name="step" value="2">
<fieldset>

<p>
	<label>顶部：新浪微博地址</label>
	<input class="text-input medium-input" type="text" name="sns_weibo" value="<?php echo isset($this->_viewer->configInfo['sns_weibo']) ? $this->_viewer->configInfo['sns_weibo'] : '';?>"/> 
	<span class="input-notification information png_bg">新浪微博链接地址</span>
</p>
<p>
	<label>顶部：邮箱地址</label>
	<input class="text-input medium-input" type="text" name="sns_mail" value="<?php echo isset($this->_viewer->configInfo['sns_mail']) ? $this->_viewer->configInfo['sns_mail'] : '';?>"/> 
	<span class="input-notification information png_bg">邮箱链接地址</span>
</p>
<p>
	<label>顶部：twitter地址</label>
	<input class="text-input medium-input" type="text" name="sns_twitter" value="<?php echo isset($this->_viewer->configInfo['sns_twitter']) ? $this->_viewer->configInfo['sns_twitter'] : '';?>"/> 
	<span class="input-notification information png_bg">twitter链接地址</span>
</p>



<p><input class="button" type="button" value="保存配置" onClick="return pagejs.setform();"/><span id="form_result"></span></p>
</fieldset>
<div class="clear"></div>
<!-- End .clear -->
</form>
</div>
<!-- End #tab2 --></div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->
<?php
$this->segment ( 'admin.footer' );
?>

<script type="text/javascript">
var pagejs = {
	setform : function(){
		if(this.formcheck()) {
			var options = {
			    dataType:	'jsonp',
			    beforeSend: function(){
					$("#form_result").html("正在提交表单，请稍候...");
			    },
			    success: function(data) {
				    data = data.data;
			    	var flag = data[0];
			    	var msg = data[1];
			    	$("#form_result").html(msg);
			    	if(flag){
			    		location.reload();
			    	}
			    }
		    };
			$('#myform').ajaxSubmit(options);
			return false;
		}
		return false;
	},
	formcheck : function(){
		return true;
	}
}
</script>