<?php
$this->segment ( 'admin.top' );
$this->segment ( 'admin.nav' );
?>
<div id="main-content">
<div class="content-box"><!-- Start Content Box -->
<div class="content-box-header">
<h3>幻灯图片</h3>
	<ul class="content-box-tabs">
        <li><a href="<?php echo $this->_viewer->baseurl . 'a=focus';?>" class="<?php echo ($this->_viewer->menuchild == 'focus') ? "default-tab" : '';?>">幻灯图片</a></li>
        <li><a href="<?php echo $this->_viewer->baseurl . 'a=focusadd';?>" class="<?php echo ($this->_viewer->menuchild == 'focusadd') ? "default-tab" : '';?>">添加图片</a></li>
   </ul>
<div class="clear"></div>
</div>
<!-- End .content-box-header -->
<div class="content-box-content">
<div class="tab-content default-tab" id="tab1">
<form name="myform" id="myform" action="<?php echo $this->_viewer->formaction;?>" method="post">
<input type="hidden" name="step" value="2">
<table>
	<thead>
		<tr>
			<th width="10">ID</th>
			<th width="200">所属类别</th>
			<th width="300">标题</th>
			<th>缩略图</th>
			<th width="100">操作</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="11">
			<div class="bulk-actions align-left">
				<span id="form_result"></span>
			</div>
			<div class="clear"></div>
			</td>
		</tr>
	</tfoot>
	<tbody>
	<?php if (!S::isArray($this->_viewer->list)){?>
		<tr>
			<td colspan="9">暂无信息！</td>
		</tr>
	<?php }else{?>
	<?php foreach ($this->_viewer->list as $k=>$v){?>
		<tr>
			<td align="center"><?php echo ($k+1);?></td>
			<td>
				<?php if(isset($v['category']) && $v['category'] >0){?>
					<?php echo isset($this->_viewer->class[$v['category']]['name']) ? $this->_viewer->class[$v['category']]['name'] : '';?>
				<?php }else{?>
					首页大图
				<?php }?>
			</td>
			<td>
				<a href="<?php echo $this->_viewer->baseurl . 'a=focusmodify&id=' . $k;?>" title="<?php echo isset($v['title']) ? $v['title'] : '-';?>">
				<?php echo isset($v['title']) ? $v['title'] : '-';?></a>
			</td>
			<td><img src="<?php echo (isset($v['pic'][1]) && $v['pic'][1]) ? $v['pic'][1] : $this->_viewer->imgpath . '/nopic.jpg';?>" width="50px" border="0"></td>
			<td align="center">
				<a href="<?php echo $this->_viewer->baseurl . 'a=focusmodify&id=' . $k;?>" title="Edit"><img src="<?php echo $this->_viewer->imgpath;?>/icons/pencil.png" alt="Edit" /></a>
				&nbsp;&nbsp;
				<a href="javascript:;" title="Delete" onClick="return pagejs.postDelete('<?php echo $this->_viewer->baseurl . 'a=focusdelete&step=2&aid=' . $k;?>');"><img src="<?php echo $this->_viewer->imgpath; ?>/icons/cross.png" alt="Delete" /></a>
			</td>
		</tr>
	<?php }?>
	<?php }?>
	
	</tbody>
</table>
</form>

</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->

<?php
$this->segment ( 'admin.footer' );
?> 

<script type="text/javascript">
var pagejs = {
	setform : function(sign){
		if(this.check_checkbox() && ((sign == 1 && confirm("确定执行该操作吗？")) || (sign == 0))) {
			var target = (event.target)?event.target:event.srcElement;
			var href = $(target).attr('href');
			$("#myform").attr('action', href);
			var options = {
			    url:        href,
			    dataType:	'jsonp',
			    beforeSend: function(){
					$("#form_result").html("正在提交表单，请稍候...");
			    },
			    success: function(data) {
				    data = data.data;
			    	var flag = data[0];
			    	var msg = data[1];
			    	$("#form_result").html(msg);
			    	if(flag){
				    	location.reload();
			    	}
			    }
		    };
			$('#myform').ajaxSubmit(options);
			return false;
		}
		return false;
	},
	check_checkbox : function(){
		if($("input[name^='aid']:checked").length){
			return true;
		}
		alert("请选择欲操作对象");
		return false;
	},
	deleteConfirm : function(){
		return confirm("确定删除该项吗？删除后将无法恢复！");
	},
	postDelete : function(url){
		if(this.deleteConfirm()){
			url += '&callback=?';
			$.getJSON(url, function(data){
				var result = data.data;
				if(result[0] == true)
					location.reload();
				else
					alert(result[1]);
			});
		}
		return false;
	}
}
</script>