<?php
$this->segment ( 'admin.top' );
$this->segment ( 'admin.nav' );
$imgpath = isset ( $this->_viewer->imgpath ) ? $this->_viewer->imgpath : '';
?>
<div id="main-content">
<div class="content-box"><!-- Start Content Box -->
<div class="content-box-header">
<h3>幻灯图片</h3>
	<ul class="content-box-tabs">
        <li><a href="<?php echo $this->_viewer->baseurl . 'a=focus';?>" class="<?php echo ($this->_viewer->currenttab == 'focus') ? "default-tab" : '';?>">幻灯图片</a></li>
        <li><a href="<?php echo $this->_viewer->baseurl . 'a=focusadd';?>" class="<?php echo ($this->_viewer->currenttab == 'focusadd') ? "default-tab" : '';?>">添加图片</a></li>
   		<?php if (isset($this->_viewer->info)){?>
   			<li><a href="#" class="<?php echo ($this->_viewer->currenttab == 'focusmodify') ? "default-tab" : '';?>">修改图片</a></li>
   		<?php }?>
   </ul>
<div class="clear"></div>
</div>
<!-- End .content-box-header -->
<div class="content-box-content">
<div class="tab-content default-tab" id="tab1">
<form name="myform" id="myform" action="<?php echo $this->_viewer->formaction;?>" method="post" enctype="multipart/form-data">
<input type="hidden" name="step" value="2">
<input type="hidden" name="id" value="<?php echo isset($this->_viewer->id) ? $this->_viewer->id : '';?>">
<fieldset>
<p><label>所属类别</label>
<select name="category" class="small-input">
	<option value="0">首页大图</option>
		<?php if (S::isArray($this->_viewer->class)){?>
		<?php foreach ($this->_viewer->class as $v){?>
			<?php if($v['depth'] != 0) continue;?>
			<option value="<?php echo $v['id'];?>" 
			<?php echo (isset($this->_viewer->info['category']) && $this->_viewer->info['category'] == $v['id']) ? 'selected' : '';?>>
			<?php echo $v['name'];?>
			</option>
		<?php }?>
		<?php }?>
</select>
</p>
<p>
	<label>标题：</label> 
	<input class="text-input medium-input" type="text" name="title" value="<?php echo isset($this->_viewer->info['title']) ? $this->_viewer->info['title'] : '';?>"/> 
	<span class="input-notification information png_bg"></span>
</p>
<p><label>图片地址：</label>
	<input type="text" class="text-input small-input" id="url" name="pic" value="<?php echo isset($this->_viewer->info['pic'][1]) ? $this->_viewer->info['pic'][1] : '';?>"> 
	<input type="button" id="fileimage" value="选择图片">
	<span class="input-notification png_bg information">最佳尺寸：1000px*450px；使用网络图片时请在文本框中填写网络图片地址；使用本地上传时文本框中请留空</span>
</p>
<p><img id="imgshow" src="<?php echo (isset($this->_viewer->info['pic'][1]) && $this->_viewer->info['pic'][1]) ? $this->_viewer->info['pic'][1] : $this->_viewer->imgpath . '/nopic.jpg';?>" width="100" border="0" alt="图片预览"></p>
<p>
	<label>图片链接地址：</label> 
	<input class="text-input medium-input" type="text" name="link" value="<?php echo isset($this->_viewer->info['link']) ? $this->_viewer->info['link'] : '';?>"/> 
	<span class="input-notification information png_bg">没有请不填</span>
</p>
<p><input class="button" type="button" value="提交保存" onClick="return pagejs.setform();"/>
<span id="form_result"></span>
</p>
</fieldset>
<div class="clear"></div>
<!-- End .clear -->
</form>
</div>
<!-- End #tab2 --></div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->

<?php
$this->segment ( 'admin.footer' );
?> 

<link rel="stylesheet" href="<?php echo $this->_viewer->editor;?>/themes/default/default.css?v1.0" type="text/css" media="screen" />
<script charset="utf-8" src="<?php echo $this->_viewer->editor;?>/kindeditor-min.js"></script>
<script charset="utf-8" src="<?php echo $this->_viewer->editor;?>/lang/zh_CN.js"></script>
<script type="text/javascript">
var editor;
$(function() {
	var editor = KindEditor.editor({
		uploadJson : '<?php echo $this->_viewer->baseurl . 'a=upload&sign=focus';?>'
	});
	$('#fileimage').click(function() {
		uploadBtn();
	});
	function uploadBtn(){
		editor.loadPlugin('image', function() {
			editor.plugin.imageDialog({
				imageUrl : $('#url').val(),
				clickFn : function(url, title, width, height, border, align) {
					$('#url').val(url);
					editor.hideDialog();
					pagejs.uploadCallBack(url, 'imgshow');
				}
			});
		});
	}
});
var pagejs = {
	uploadCallBack : function(url, id){
		$("#" + id).attr('src', url);
	},
	setform : function(){
		if(this.formcheck()) {
			var options = {
			    dataType:	'jsonp',
			    beforeSend: function(){
					$("#form_result").html("正在提交表单，请稍候...");
			    },
			    success: function(data) {
				    data = data.data;
			    	var flag = data[0];
			    	var msg = data[1];
			    	$("#form_result").html(msg);
			    	if(flag){
		    		<?php if(isset($this->_viewer->info)){?>
			    		location.reload();
			    	<?php }else{?>
			    		$('#myform').resetForm();
			    	<?php }?>
			    	}
			    }
		    };
			$('#myform').ajaxSubmit(options);
			return false;
		}
		return false;
	},
	formcheck : function(){
		return true;
	}
}
</script>