<?php
$this->segment ( 'admin.top' );
$this->segment ( 'admin.nav' );
?>
<div id="main-content">
<div class="content-box"><!-- Start Content Box -->
<div class="content-box-header">
<h3>帐号管理</h3>
	<ul class="content-box-tabs">
        <li><a href="<?php echo $this->_viewer->baseurl . 'a=manager';?>" class="<?php echo ($this->_viewer->currenttab == 'manager') ? "default-tab" : '';?>">帐号管理</a></li>
        <li><a href="<?php echo $this->_viewer->baseurl . 'a=manageradd';?>" class="<?php echo ($this->_viewer->currenttab == 'manageradd') ? "default-tab" : '';?>">添加管理员</a></li>
   </ul>
<div class="clear"></div>
</div>
<!-- End .content-box-header -->
<div class="content-box-content">
<div class="tab-content default-tab" id="tab1">
<form name="myform" id="myform" action="<?php echo $this->_viewer->formaction;?>" method="post">
<input type="hidden" name="step" value="2">
<table>
	<thead>
		<tr>
			<th width="10">ID</th>
			<th width="100" align="center">用户名</th>
			<th>上次登录时间</th>
			<th width="">上次登录IP</th>
			<th width="80">登录次数</th>
			<th width="200">添加日期</th>
			<th width="100">操作</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="7">
			<div class="bulk-actions align-left">
				<span id="form_result"></span>
			</div>
			<?php echo $this->_viewer->pageNav;?>
			<div class="clear"></div>
			</td>
		</tr>
	</tfoot>
	<tbody>
	<?php if (!S::isArray($this->_viewer->list)){?>
		<tr>
			<td colspan="7">暂无信息！</td>
		</tr>
	<?php }else{?>
	<?php foreach ($this->_viewer->list as $v){?>
		<tr>
			<td><?php echo isset($v['id']) ? $v['id'] : '-';?></td>
			<td  align="center">
				<a href="<?php echo $this->_viewer->baseurl . 'a=managermodify&id=' . $v['id'];?>" title="<?php echo isset($v['username']) ? $v['username'] : '-';?>">
				<?php echo isset($v['username']) ? $v['username'] : '-';?></a>
			</td>
			<td align="center"><?php echo $v['last_date'] ? date('Y-m-d H:i:s', $v['last_date']) : '未曾登录';?></td>
			<td><?php echo isset($v['last_ip']) ? $v['last_ip'] : '0.0.0.0';?></td>
			<td><?php echo isset($v['total_num']) ? $v['total_num'] : '0';?></td>
			<td align="center"><?php echo date('Y-m-d H:i:s', $v['created_time']);?></td>
			<td align="center">
				<a href="<?php echo $this->_viewer->baseurl . 'a=managermodify&id=' . $v['id'];?>" title="Edit"><img src="<?php echo $this->_viewer->imgpath;?>/icons/pencil.png" alt="Edit" /></a>
				&nbsp;&nbsp;
				<a href="javascript:;" title="Delete" onClick="return pagejs.postDelete('<?php echo $this->_viewer->baseurl . 'a=managerdelete&step=2&aid=' . $v['id'];?>');"><img src="<?php echo $this->_viewer->imgpath; ?>/icons/cross.png" alt="Delete" /></a>
			</td>
		</tr>
	<?php }?>
	<?php }?>
	
	</tbody>
</table>
</form>

</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->

<?php
$this->segment ( 'admin.footer' );
?> 

<script type="text/javascript">
var pagejs = {
	setform : function(sign){
		if(this.check_checkbox() && ((sign == 1 && confirm("确定执行该操作吗？")) || (sign == 0))) {
			var target = (event.target)?event.target:event.srcElement;
			var href = $(target).attr('href');
			$("#myform").attr('action', href);
			var options = {
			    url:        href,
			    dataType:	'jsonp',
			    beforeSend: function(){
					$("#form_result").html("正在提交表单，请稍候...");
			    },
			    success: function(data) {
				    data = data.data;
			    	var flag = data[0];
			    	var msg = data[1];
			    	$("#form_result").html(msg);
			    	if(flag){
				    	location.reload();
			    	}
			    }
		    };
			$('#myform').ajaxSubmit(options);
			return false;
		}
		return false;
	},
	check_checkbox : function(){
		if($("input[name^='aid']:checked").length){
			return true;
		}
		alert("请选择欲操作对象");
		return false;
	},
	deleteConfirm : function(){
		return confirm("确定删除该项吗？删除后将无法恢复！");
	},
	postDelete : function(url){
		if(this.deleteConfirm()){
			url += '&callback=?';
			$.getJSON(url, function(data){
				var result = data.data;
				if(result[0] == true)
					location.reload();
				else
					alert(result[1]);
			});
		}
		return false;
	}
}
</script>