<?php
$this->segment ( 'admin.top' );
$this->segment ( 'admin.nav' );
?>
<div id="main-content">
<div class="content-box"><!-- Start Content Box -->
<div class="content-box-header">
<h3>情书管理</h3>
	<ul class="content-box-tabs">
        <li><a href="<?php echo $this->_viewer->baseurl . 'a=shows';?>" class="<?php echo ($this->_viewer->menuchild == 'shows') ? "default-tab" : '';?>">情书管理</a></li>
   </ul>
<div class="clear"></div>
</div>
<!-- End .content-box-header -->
<div class="content-box-content">
<div class="tab-content default-tab" id="tab1">
<form name="myform" id="myform" action="<?php echo $this->_viewer->formaction;?>" method="post">
<input type="hidden" name="step" value="2">
<table>
	<thead>
		<tr>
			<th width="10">ID</th>
			<th width="50">状态</th>
			<th width="50">类别</th>
			<th width="200">标题</th>
			<th width="100">用户</th>
			<th width="100">缩略图</th>
			<th width="50">支持</th>
			<th width="50">分享</th>
			<th width="50">评论</th>
			<th width="50">点击</th>
			<th width="100">发表时间</th>
			<th width="100">操作</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="12">
			<div class="bulk-actions align-left">
				<span id="form_result"></span>
			</div>
			<div class="clear"></div>
			</td>
		</tr>
	</tfoot>
	<tbody>
	<?php if (!S::isArray($this->_viewer->list)){?>
		<tr>
			<td colspan="12">暂无信息！</td>
		</tr>
	<?php }else{?>
	<?php foreach ($this->_viewer->list as $v){?>
		<tr>
			<td align="center"><?php echo $v['id'];?></td>
			<td align="center"><?php echo isset($v['status']) ? ($v['status'] ? "<span class='font_green'>√</span>" : "<span class='font_red'>×</span>") : '-';?></td>
			<td><?php echo isset($this->_viewer->showTypes[$v['type']]) ? $this->_viewer->showTypes[$v['type']] : '';?></td>
			<td>
				<a href="<?php echo $this->_viewer->baseurl . 'a=showsmodify&id=' . $v['id'];?>" title="<?php echo isset($v['title']) ? $v['title'] : '-';?>">
				<?php echo isset($v['title']) ? $v['title'] : '-';?></a>
			</td>
			<td><?php echo isset($this->_viewer->userInfos[$v['uid']]['username']) ? $this->_viewer->userInfos[$v['uid']]['username'] : '';?></td>
			<td><img src="<?php echo (isset($v['pic']) && $v['pic']) ? $v['pic'] : $this->_viewer->imgpath . '/nopic.jpg';?>" width="50px" border="0"></td>
			<td align="center"><?php echo $v['hold'];?></td>
			<td align="center"><?php echo $v['share'];?></td>
			<td align="center"><?php echo $v['comment'];?></td>
			<td align="center"><?php echo $v['hit'];?></td>
			<td align="center"><?php echo date('Y-m-d H:i:s', $v['created_time']);?></td>
			<td align="center">
				<a rel="facebox" href="<?php echo $this->_viewer->baseurl . 'a=showsdetail&id=' . $v['id'];?>" title="Edit"><img src="<?php echo $this->_viewer->imgpath;?>/icons/pencil.png" alt="Edit" /></a>
				&nbsp;&nbsp;
				<a href="javascript:;" title="Delete" onClick="return pagejs.postDelete('<?php echo $this->_viewer->baseurl . 'a=showsdelete&step=2&id=' . $v['id'];?>');"><img src="<?php echo $this->_viewer->imgpath; ?>/icons/cross.png" alt="Delete" /></a>
			</td>
		</tr>
	<?php }?>
	<?php }?>
	
	</tbody>
</table>
</form>

</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->

<?php
$this->segment ( 'admin.footer' );
?> 
<script>
$(document).ready(function(){
	$("a[rel*=facebox]").live('click', function(){
		var url = $(this).attr('href');
		$.get(url, function(data) { $.facebox(data) })
		return false;
	})
	//jQuery.facebox(function($) { 
	//	$.get(url, function(data) { $.facebox(data)});
	//})
})
</script>
