<div class="content-box"><!-- Start Content Box -->
<div class="content-box-header">
<h3>情书详情</h3>
	<ul class="content-box-tabs">
        <li><a href="<?php echo $this->_viewer->baseurl . 'a=shows';?>" class="<?php echo ($this->_viewer->menuchild == 'shows') ? "default-tab" : '';?>">情书管理</a></li>
   </ul>
<div class="clear"></div>
</div>

<div class="content-box-content">
	<div class="tab-content default-tab">
	<fieldset>
	<p>
		标题：
		【<?php echo isset($this->_viewer->showTypes[$this->_viewer->showInfo['type']]) ? $this->_viewer->showTypes[$this->_viewer->showInfo['type']] : '';?>】
		<?php echo isset($this->_viewer->showInfo['title']) ? $this->_viewer->showInfo['title'] : '';?>
	</p>
	<p>
		发表时间：
		<?php echo isset($this->_viewer->showInfo['created_time']) ? date('Y-m-d H:i:s', $this->_viewer->showInfo['created_time']) : '';?>
	</p>
	<p>
		数据统计：
		点击数：<?php echo $this->_viewer->showInfo['hit'];?>
		支持数：<?php echo $this->_viewer->showInfo['hold'];?>
		分享数：<?php echo $this->_viewer->showInfo['share'];?>
		评论数：<?php echo $this->_viewer->showInfo['comment'];?>
		单用户评论数：<?php echo $this->_viewer->showInfo['ucomment'];?>
	</p>
	<p>
		图片模板：
		<img id="imgshow" src="<?php echo (isset($this->_viewer->showInfo['pic']) && $this->_viewer->showInfo['pic']) ? $this->_viewer->showInfo['pic'] : $this->_viewer->imgpath . '/nopic.jpg';?>" width="100" border="0" alt="图片预览">
	</p>
	<?php if($this->_viewer->showInfo['type'] == SystemConst::SHOW_TYPE_TEXT){?>
	<p><label>情书内容</label> 
		<textarea class="text-input textarea" name="content"><?php echo isset($this->_viewer->showInfo['content']) ? $this->_viewer->showInfo['content'] : '';?></textarea>
	</p>
	<?php }?>
	<?php if($this->_viewer->showInfo['type'] == SystemConst::SHOW_TYPE_SOUND){?>
	<p><label>情书音频文件</label> 
		<?php echo isset($this->_viewer->showInfo['url']) ? $this->_viewer->showInfo['url'] : '';?>
	</p>
	<?php }?>
	<?php if($this->_viewer->showInfo['type'] == SystemConst::SHOW_TYPE_VIDEO){?>
	<p><label>情书视频文件</label> 
		<?php echo isset($this->_viewer->showInfo['url']) ? $this->_viewer->showInfo['url'] : '';?>
	</p>
	<?php }?>
	
	</fieldset>
	</div>
</div>

<?php
//$this->segment ( 'admin.footer' );
?>