<?php if (isset($this->_viewer->config['site-access-code']) && $this->_viewer->config['site-access-code']){
	echo '<div class="hide">' . $this->_viewer->config['site-access-code'] . '</div>';
}?>
</body>
</html>
<script type="text/javascript" src="<?php echo $this->_viewer->jspath;?>/jquery-1.7.2.js"></script>
<script type="text/javascript" src="<?php echo $this->_viewer->jspath;?>/userdefine.js"></script>
<script type="text/javascript">
$(document).ready(function(){
})
var url = new Array();
for (i = 1; i < url.length; i++){
	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	ga.src = url[i];
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
};
</script>

