<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title><?php echo $this->_viewer->title;?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="Keywords" content="<?php echo isset($this->_viewer->config['webseokeyword']) ? $this->_viewer->config['webseokeyword'] : '';?>">
<meta name="Description" content="<?php echo isset($this->_viewer->config['webseodescription']) ? $this->_viewer->config['webseodescription'] : '';?>">

<!-- Le styles -->
<link href="<?php echo $this->_viewer->csspath;?>/core.css" rel="stylesheet">
<link href="<?php echo $this->_viewer->csspath;?>/style.css" rel="stylesheet">
<!--[if IE]>
<style>
@font-face {
	font-family: "F_DEFINED";
	src: url("<?php echo $this->_viewer->csspath;?>/FONTS/L_10646.EOT");
}
</style>
<!--[if lte IE 6]>
<script src="<?php echo $this->_viewer->jspath;?>/DD_belatedPNG_0.0.8a.js" type="text/javascript"></script> 
<script type="text/javascript">
DD_belatedPNG.fix('div, ul, img, li, input, a, button, .pngbg'); 
</script>
<![endif]-->

</head>

<body class="bg1">
